version: '3.7'

services:
    backend:
      build: ./backend
      restart: unless-stopped
    frontend:
      depends_on:
        - backend
      build:
        context: ./frontend
    nginx:
      image: nginx:latest
      container_name: webserver
      restart: unless-stopped
      depends_on:
        - frontend
        - backend
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./nginx/local.conf:/etc/nginx/nginx.conf

